### PR TITLE
Update to Scala 2.10.6

### PR DESCRIPTION
**Pull request by zczapran**
The release didn't bring any groundbreaking changes, but it would still be nice to update to the latest.

### CODE REVIEW

**Comment by malcolmgreaves** [comment]
Nice catch! Didn't realize 2.10.6 was out. We can merge this directly.

**Comment by pkinsky** [comment]
Awesome, thanks.

**Comment by zczapran** [comment]
Sure thing, feel free to merge it.

**Comment by malcolmgreaves** [comment]
+1 @zczapran

**Pull request merged**
