### PR TITLE
Ability to use inter-dependent schemas defined in multiple files

### PR DESCRIPTION
**Pull request by ebiggs**
Addresses Issue #3 "Inability to use inter-dependent schemas defined in multiple files" by creating a spray-json based avro parser using Scala idioms, that is less strict than the org.apache.avro.Schema.Parser.

### CODE REVIEW

**Comment by ebiggs** [comment]
With this last test case I now consider this thoroughly QA'd.

**Comment by malcolmgreaves** [comment]
Nice work @ebiggs ! @pkinsky and I will review this over the next day or two. Sound good?

**Comment by ebiggs** [comment]
Thanks @malcolmgreaves, appreciate it.

**Comment by pkinsky** [comment]
@ebiggs awesome, we'll review over the next few days. Out of curiosity (I'll try to add a test later), what would happen if circular references are introduced?

```
{ "type": "record", "name": "A", "fields": [{ "name": "b", "type": "B" }] }

{ "type": "record", "name": "B", "fields": [{ "name": "a", "type": "A" }] }
```

**Comment by ebiggs** [comment]
@pkinsky if those are two partials, it will get resolved when selecting the root referable (required), i.e.: 

avModule("A") shouldBe { "type": "record", "name": "A", "fields": [{ "name": "b", "type": { "type": "record", "name": "B", "fields": [{ "name": "a", "type": "A" }] } }] } 

avModule("B") shouldBe { "type": "record", "name": "B", "fields": [{ "name": "a", "type": { "type": "record", "name": "A", "fields": [{ "name": "b", "type": "B" }] } }] }

Otherwise, they get dereferenced in order of appearance (i.e. if they are both in a union or fields of a record the one appearing first gets dereferenced as above)

**Comment by malcolmgreaves** [comment]
Awesome stuff Eric! The results of my review are here: https://github.com/ebiggs/avro-codegen/pull/1

**Comment by ebiggs** [comment]
Merged your PR @malcolmgreaves

**Comment by malcolmgreaves** [comment]
LGTM

**Comment by pkinsky** [comment]
LGTM

**Comment by malcolmgreaves** [comment]
Congrats on the first successful community PR @ebiggs ! Thank you so much for your work!

**Comment by pkinsky** [comment]
Thank you for your excellent contribution, @ebiggs!

**Pull request merged**
