### PR TITLE
Sbt scripted tests

### PR DESCRIPTION
**Pull request by javierarrieta**
Moved e2e to scripted tests

### CODE REVIEW

**Comment by malcolmgreaves** [comment]
Hey @javierarrieta , nice work. I think there might be a problem, however. Looking in the build logs, I don't see the expected output from the e2e tests. In the most recent build, you can see the output: https://travis-ci.org/Nitro/avro-codegen/builds/97113276 .

**Comment by malcolmgreaves** [comment]
Examples:

**Comment by javierarrieta** [comment]
Yeah, I saw that when I migrated it, it does not output anything but I verified the tests were run. I will try to investigate how to make sbt output the scripted tests results and come back

**Comment by javierarrieta** [comment]
@malcolmgreaves @pkinsky Any objection to merge this?

**Comment by malcolmgreaves** [comment]
@javierarrieta nope, looks great! thanks for the PR. Merging now.

**Pull request merged**
